Repository gisaia/ARLAS-wui-toolkit, pull requests merged in 2018-12, with the labels that each got.

#95 import rootContributorConf json schema from contributors as last one
  src/app/services/startup/startup.service.ts
Labels: documentation, type:maintenance

#96 Feauture/improve startup service
  src/app/components/errormodal/errormodal.component.ts
  src/app/services/startup/startup.service.ts
Labels: type:enhancement

#97 Document the components
  src/app/components/analytics-board/analytics-board.component.ts
  src/app/components/analytics-board/analytics.utils.ts
  src/app/components/errormodal/errormodal.component.ts
  src/app/components/language-switcher/language-switcher.component.ts
  src/app/components/share/share.component.ts
  src/app/components/tag/tag.component.ts
  src/app/components/timeline/date-picker/date-picker.component.html
  src/app/components/timeline/date-picker/date-picker.component.ts
  src/app/components/timeline/timeline-shortcut/timeline-shortcut.component.ts
  src/app/components/timeline/timeline/timeline.component.ts
  src/app/components/timeline/timeline/timeline.utils.ts
  src/app/components/widget/widget.component.ts
  src/app/services/startup/startup.service.ts
Labels: type:maintenance

#100 Add a class for AB group size
  src/app/app.component.ts
  src/app/components/analytics-board/analytics-board.component.html
  src/config.json
Labels: type:enhancement
