Repository gisaia/ARLAS-wui-toolkit, pull requests merged in 2019-01, with the labels that each got.

#103 Fix versions image mkdoc
  mkDocs.sh
Labels: type:bug

#102 Add a 'compact' mode to the analytics board
  package-lock.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/components/analytics-board/analytics-board.component.css
  src/app/components/analytics-board/analytics-board.component.html
  src/app/components/analytics-board/analytics-board.component.spec.ts
  src/app/components/analytics-board/analytics-board.component.ts
  src/app/components/timeline/timeline-shortcut/timeline-shortcut.component.css
  src/app/components/timeline/timeline-shortcut/timeline-shortcut.component.html
  src/app/components/timeline/timeline/timeline.component.css
  src/config.json
Labels: type:enhancement

#105 Add new input in powerbar widget
  package-lock.json
  package.json
  src/app/components/widget/widget.component.html
  src/config.json
Labels: type:enhancement

#106 Fix arlas version in package release
  package-lock.json
  package-release.json
Labels: type:maintenance

#107 Fix typo in powerbars widget
  src/app/components/widget/widget.component.html
Labels: type:bug

#109 Fix viewBookmark method
  src/app/services/bookmark/bookmark.service.ts
  src/app/services/bookmark/bookmarkDatabase.ts
Labels: type:bug

#110 Integrate TreeContributor
  package-lock.json
  package-release.json
  package.json
  src/app/components/analytics-board/analytics-board.component.html
  src/app/components/widget/widget.component.html
  src/app/components/widget/widget.component.spec.ts
  src/app/components/widget/widget.component.ts
  src/app/services/startup/arlasconfig.schema.json
  src/app/services/startup/contributorBuilder.ts
  src/app/services/startup/startup.service.ts
  src/config.json
Labels: type:breaking

#111 Create ArlasColorGeneratorLoader injected to powerbars/donuts/list
  package-lock.json
  package-release.json
  package.json
  src/app/app.module.ts
  src/app/components/widget/widget.component.html
  src/app/components/widget/widget.component.ts
  src/app/services/color-generator-loader/color-generator-loader.service.spec.ts
  src/app/services/color-generator-loader/color-generator-loader.service.ts
  src/app/services/startup/arlasconfig.schema.json
  src/config.json
Labels: type:breaking, type:enhancement
